# Generated by Django 4.2.1 on 2023-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
