# Generated by Django 4.2.1 on 2023-09-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playtime',
            old_name='persona_id',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='persona_id',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='quizanswertime',
            old_name='persona_id',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='quizorder',
            old_name='persona_id',
            new_name='person_id',
        ),
    ]
