# Generated by Django 4.2.1 on 2023-09-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_playtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtime',
            name='play_time',
            field=models.CharField(max_length=30),
        ),
    ]
