# Generated by Django 4.2.1 on 2023-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_playtime_play_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
