# Generated by Django 4.2.1 on 2023-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quizanswertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=30)),
                ('q2_que', models.CharField(max_length=30)),
                ('q2_ans', models.CharField(max_length=30)),
                ('q3', models.CharField(max_length=30)),
                ('q4', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
