# Generated by Django 4.2.1 on 2023-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_index', models.CharField(max_length=20)),
                ('id_1', models.CharField(max_length=20)),
                ('id_2', models.CharField(max_length=20)),
                ('id_3', models.CharField(max_length=20)),
                ('id_4', models.CharField(max_length=20)),
                ('id_5', models.CharField(max_length=20)),
                ('id_6', models.CharField(max_length=20)),
            ],
        ),
    ]
